# Generated by Django 5.2.7 on 2025-10-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Low')], default='Low', max_length=50),
            preserve_default=False,
        ),
    ]
